### PR TITLE
Fixed up the no_ping module

### PR DESCRIPTION
**Pull request by Vankka**
This is untested, but functions & fields should atleast be correct as I wrote this in a IDE

#### What does it do?
- Bots, webhooks (webhooks don't have associated member, thus would cause errors) and staff can mention whoever they want
- Only lets people ping members who have talked in the past 50 messages or 2.5 hours
- Has a **commented out** if-block to allow preventing mentioning staff if they haven't mentioned the normal-user (eg. staff have to mention a user before they are able to mention the staff (in the 50 messages or 2.5 hours)) that can be taken into action later if wanted
 
#### Potential future consideration
Discord might not like constantly retrieving the past 50 messages (though I think discord.js might cache messages, not sure though)

### CODE REVIEW

**Comment by Rsl1122** [comment]
[Documentation of fetchMessages](https://discord.js.org/#/docs/main/v11/class/TextChannel?scrollTo=fetchMessages) suggests that the messages are cached

**Comment by Vankka** [comment]
> I think it removes the check against @me in the nickname, because that was an issue at one point (where someone has @me in their nick and the bot scolds for pinging them)

I don't think this is a issue since everything works with user ids, and Discord uses special formatting for mentions `<@userid>` ([docs](https://discord.com/developers/docs/reference#message-formatting-formats)), thus I don't think having that check was neccasery

**Comment by Rsl1122** [comment]
Ah I might have been a bit unclear - I mean the following scenario:

- A user has a nick say `Free to chat | @me`
- Another user (Bob#1111) mentions `@Free to chat | @me#1432`
- The bot scolds Bob#1111 for mentioning the first user even though they have `@me` in their name

**Comment by Vankka** [comment]
Ah so the point is to allow mentioning users that have `@me` in their name regardless of if they have spoken? Then this would do the trick
```
            .filter(member => !member.nickname || !member.nickname.toLowerCase().indexOf("@me") === -1)
```
(would be placed after `msg.mentions.members`. indexOf returns -1 when the sequence isn't present)

**Pull request merged**
